version: '2'
services:
  py:
    build: .
    image: "py"
    volumes:
     - .:/code
    #command: python main.py
	# other handy stuff:
  mongo:
    image: "mongo"
    #ports:
    # - "27017:27017"
  rabbitmq:
    image: "rabbitmq:management-alpine"
		# admin dashboard http://localhost:8080/ user:guest pw:guest
    ports:
     - "8080:15672"
	postgres:
    image: postgres
    #ports:
    #  - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
